name 'library'
maintainer 'Andreas Rytina'
maintainer_email 'andy.rytina@gmail.com'
license 'All Rights Reserved'
description 'Installs/Configures library'
version '0.1.0'
chef_version '>= 16.0'
depends 'apt'
depends 'postgresql'
depends 'pg'
